DEFAULT_TEMPERATURE = 0.5
DEFAULT_MAX_NEW_TOKENS = 2500
DEFAULT_REPETITION_PENALTY = 1.1
DEFAULT_FREQUENCY_PENALTY = 0.5

RETRY_TRIES = 8
# NUMBER_OF_COLUMNS_WIDGETS = 2

EMPTY_KEYS_IMP = 9
EMPTY_CONTENT = 8
WEIGHT_USUC = 0.5


ZERO_SCORE = 0
GEN_RESPONSE_TEMP = 0.5
GEN_RESPONSE_MAX_TOKENS = 2500
GEN_RESPONSE_REPETITION_PENALTY = 1.0
GEN_RESPONSE_FREQUENCY_PENALTY = 1.0
GEN_RESPONSE_TOP_K = 60
GEN_RESPONSE_TOP_N_TOKENS = 5
GEN_RESPONSE_TOP_P = 0.8
